sudo: false
language: go
go:
- 1.5
go_import_path: github.com/octoblu/circularqueue
services:
- redis
before_install:
- wget https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm && chmod +x gpm && sudo mv gpm /usr/local/bin
install:
- gpm install
script:
- ginkgo -cover
